# Generated by Django 5.2.5 on 2025-08-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.phrase'),
        ),
        migrations.AlterField(
            model_name='like',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.phrase'),
        ),
    ]
